# Generated by Django 4.2 on 2023-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vale_consumo', '0003_alter_solicitud_retira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='id',
        ),
        migrations.AddField(
            model_name='recurso',
            name='cod_recurso',
            field=models.CharField(default='AAAAAAAA1', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
