# Generated by Django 4.2 on 2023-04-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('vale_consumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familia', models.CharField(max_length=100)),
                ('is_active', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventaro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inventario', models.DateField(blank=True, null=True)),
                ('is_active_inventario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Inventario',
            fields=[
                ('id_detalle_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_inventariada', models.IntegerField()),
                ('no_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
                ('recurso_inventariado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vale_consumo.recurso')),
            ],
            options={
                'verbose_name': 'Detalle de inventario',
                'verbose_name_plural': 'Detalle de inventarios',
            },
        ),
    ]
